In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
arr2 = np.array([[1,2,3], [4,5,6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
#Check Number of Dimensions
print(arr2.ndim)

2


In [5]:
#create 'n' no. of dimensional array
arr5 = np.array([1,2,3,4,5], ndmin=5)
print(arr5.ndim)

5


In [6]:
print(arr[0])
print(arr2[1,1])
print(arr2[1,-1])

1
5
6


In [7]:
print(arr[2] + arr[3])

7


In [8]:
print(arr[1:3])

[2 3]


In [9]:
# stepsize (skiping elements)
print(arr[1:5:2])

[2 4]


In [34]:
# creating array with same number in all elements
print(np.zeros((2,2)))
print(np.ones((2,3), dtype='i'))
print(np.full((2,4), 6, dtype='float'))

[[0. 0.]
 [0. 0.]]
[[1 1 1]
 [1 1 1]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [39]:
# Repeat an array
def repeat():
    arr = np.array([[1,2,3]])
    r1 = np.repeat(arr,3, axis=0)
    print(r1)
repeat()

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [11]:
#numpy datatype
print(arr.dtype)
print(np.array(['a','b','c']).dtype)
print(np.array([1,'b','c']).dtype)

int32
<U1
<U11


In [12]:
#it will change any data entered to assigned datatype
print(np.array([1,2,3], dtype='f'))

[1. 2. 3.]


In [13]:
#shape of array
# first refers to no. of dimensions and second refers to no. of elements in each dimension
# NOTE: it won't show no. of elements unless it is equal in every dimension
print(np.array([[1,2,3], [4,5,6]]).shape)

(2, 3)


In [42]:
# copying tha array
# ALWAYS use copy function while copying!!!!!
def copy():
    a = np.array([1,2,3])
    b = a.copy()
    b[0] = 10
    print(a,b)
copy()

[1 2 3] [10  2  3]


In [14]:
# iterating through ndarray. it iterate thorugh 'n' dimensions without nested loops 
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [15]:
# iterating through ndarray while changing datatype only temporarily
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['float']):
    print(x)

1.0
2.0
3.0
4.0
5.0
6.0


In [16]:
# it iterate through ndarray along with naming its position(index)
for idx, x in np.ndenumerate(arr2):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [17]:
def con():
    a = np.array([['a','b'],['c','d']])
    b = np.array([['e','f'],['g','h']])
    print(np.concatenate((a,b),axis=1))
con()

[['a' 'b' 'e' 'f']
 ['c' 'd' 'g' 'h']]


In [18]:
def stack():
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    arr = np.stack((arr1, arr2), axis=1)
    print(arr)
stack()

[[1 4]
 [2 5]
 [3 6]]


In [19]:
# splits the array in 'n' parts. NOTE: it only works if array can be equally divided
def split():
    arr = np.array([1,2,3,4,5,6])
    newarr = np.split(arr, 3)
    for x in newarr:
        print(x)
    print('\n')
split()

# array_split works even if array cannot be equally divided
def arr_split():
    arr = np.array([1,2,3,4,5,6,7,8,9])
    newarr = np.array_split(arr,4)
    for x in newarr:
        print(x)
arr_split()

[1 2]
[3 4]
[5 6]


[1 2 3]
[4 5]
[6 7]
[8 9]


In [20]:
# searching on which index is the given condition is
def search():
    arr = np.array([1,2,3,4,5,6,4,4])
    print(np.where(arr == 4))
    print(np.where(arr%2 == 0))
search()

(array([3, 6, 7], dtype=int64),)
(array([1, 3, 5, 6, 7], dtype=int64),)


In [21]:
# it is used to find suitable indices where number would be inseted for maintaining sorted array
def searchsort():
    arr = np.array([6, 8, 7, 9])
    x = np.searchsorted(arr, 7)
    print(x)
searchsort()

1


In [22]:
def filter():
    arr = np.array([41,42,43,44])
    print(arr[arr > 42])
filter()

[43 44]


In [23]:
def random():
    print(np.random.randint(100)) # random integer from 0 to 100
    print(np.random.rand()) # random float from 0 to 1
    print(np.random.randint(100, size=(4))) # array containing random 4 integers
random()

19
0.04716253361976219
[60 66 97 96]


In [24]:
def choice():
    print(np.random.choice([3,7,1,9])) # picking random element from given array
choice()

9
