In [3]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6])

print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
arr2 = np.array([[1,2,3], [4,5,6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
#Check Number of Dimensions
print(arr2.ndim)

2


In [15]:
#create 'n' no. of dimensional array
arr5 = np.array([1,2,3,4,5], ndmin=5)
print(arr5.ndim)

5
